### ISSUE TITLE
TensorRT?

### ISSUE THREAD

**Issue by turowicz** [SciSharp/SciSharp#1]
NVIDIA is transitioning their inference stack recommendations to TensorRT. Is there a plan to include it in SciSharp?

**Comment by Oceania2018** [comment]
@turowicz TensorRT is support in the C binary level. I think it's nNothing to do with C# binding.
You have to compile the TensorRT optimized version as https://github.com/tensorflow/tensorrt.

**Comment by turowicz** [comment]
Right thanks!
